API/urls.py
from django.urls import path, include

app_name = "api"

urlpatterns = [
    path('payment/', include("API.payment.urls", namespace="payment_api")),
    path('', include("API.product.urls", namespace="api_product")),
    path('user/',include("API.user.urls",namespace="user_api"))
]

API/user/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views


app_name = 'user_api'

urlpatterns = [
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

Online_Store_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#outh
# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView


from .views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name="home"),
    path('product/', include('Product.urls', namespace='product')),
    path('news/', include('News.urls', namespace="news")),
    path('salesman/', include('Salesman.urls', namespace="salesman")),
    path('user/', include('User.urls', namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('Payment.urls', namespace="Payment")),
    #ouath :
    # path('o', TemplateView.as_view(template_name="outh.html")),
    # path('o/accounts/', include('allauth.urls')),
    # path('o/logout', LogoutView.as_view()),
    path('api/', include('API.urls',namespace="api"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Salesman/urls.py
from django.urls import path
from django.contrib import admin
from .views import SignUpView, ChangeView, Done

app_name = "salesman"

urlpatterns = [
    path('login/', admin.site.urls),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('change/', ChangeView.as_view(), name='change'),
    path('done/', Done.as_view(), name='done'),
]

User/urls.py
from unicodedata import name
from django.urls import path

from .views import (LoginRegisterView, WaitingForVerify, activate,
                    ForgetPassword, PasswordReset, logout, UserProfileView ,Factor)

app_name = "user"

urlpatterns = [
    path('verify/', WaitingForVerify.as_view(), name='verify'),
    path('login_register/', LoginRegisterView.as_view(), name='login_register'),
    path('logout/', logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),
    path('forget_password/', ForgetPassword.as_view(), name="forget_password"),
    path('passwordreset/', PasswordReset.as_view(), name='passwordresest'),
    path('profile/',UserProfileView.as_view(),name="profile"),
    path('factor/<int:id>/',Factor.as_view(),name="factor")
]

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import CustomUserManager


class Profile(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=True)
    phone_number = models.CharField(max_length=11, null=True, unique=True)
    is_active = models.BooleanField(default=False)
    is_salesman = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return self.email


class Customer(Profile):
    TYPE = [
        ("WC", "Wandering_customer"),
        ("IC", "Impulsive_customer"),
        ("DC", "Discount_customer"),
        ("LC", "Loyal_customer"),
    ]
    type = models.CharField(max_length=30, choices=TYPE, default="WC")
    img = models.ImageField(upload_to='customer/profile', null=True)

    class Meta:
        db_table = 'customer'


class Admin(Profile):
    class Meta:
        db_table = 'admin'


class CustomerAddress(models.Model):
    address = models.TextField()
    postal_code = models.CharField(max_length=10)
    geographical_location = models.CharField(max_length=50)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return self.customer.email


class UserDevice(models.Model):
    device_type = models.CharField(max_length=256, null=True)
    os_type = models.CharField(max_length=256, null=True)
    device_brand = models.CharField(max_length=256, null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="device")
    last_login = models.DateField(auto_now=True, null=True)

    class Meta:
        unique_together = ('device_type', 'os_type', 'device_brand')

User/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm

from User.models import Customer

User = get_user_model()


class LoginFormm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError("Please confirm your email so you can log in.", code='inactive')


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class EmailSignUpForm(UserCreationForm):
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Customer
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


class RestPasswordForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user = User.objects.get(email=email)
        if user:
            self.cleaned_data["user"] = user
            return self.cleaned_data['email']
        else:
            raise forms.ValidationError("user not found")


class UserUpdateProfile(forms.Form):
    first_name = forms.CharField(max_length=256)
    last_name = forms.CharField(max_length=256)
    eamil = forms.EmailField()
    password1 = forms.CharField(max_length=100)
    password2 = forms.CharField(max_length=100)
    old_password = forms.CharField(max_length=100)


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = Customer
        fields = ['email', 'phone_number', 'type', 'img', 'first_name', 'last_name']
        widgets = {
            'email': forms.TextInput(attrs={'readonly': 'readonly'}),
            'type': forms.TextInput(attrs={'readonly': 'readonly'})
        }

User/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login as _login, logout as _logout
from django.core.cache import caches
from django.shortcuts import redirect, render
from django.views.generic import View
from django.urls import reverse_lazy, reverse
from django.contrib.auth.forms import SetPasswordForm
from django.http.response import JsonResponse
from django.utils.decorators import method_decorator

from User.models import UserDevice
from Payment.models import Wallet, History
from .forms import EmailSignUpForm, LoginForm, RestPasswordForm, UserUpdateForm
from .utils import genrate_user_device, token_validator, email_message_generator
from .tasks import email_sender

User = get_user_model()


class LoginRegisterView(View):

    def get(self, request):
        login_form = LoginForm()
        register_form = EmailSignUpForm()
        ctx = {'login_form': login_form, 'register_form': register_form}
        return render(request, "user/signup_login.html", context=ctx)

    def post(self, request):
        status = request.POST.get('status')

        if status == 'login':
            login_form = LoginForm(request.POST)
            next_url = request.POST.get("next_url")
            if login_form.is_valid():
                email = login_form.cleaned_data.get("email")
                password = login_form.cleaned_data.get("password")
                user = authenticate(request, email=email, password=password)
                if user is not None:
                    genrate_user_device(request, user)
                    redis_cache = caches['default']
                    redis_client = redis_cache.client.get_client()
                    try:
                        cart = redis_client.hgetall(request.session.session_key)
                        redis_client.hset(request.user.USERNAME_FIELD, mapping=cart)
                    except:
                        pass
                    _login(request, user)
                    if next_url:
                        return redirect(next_url)
                    else:
                        return redirect(reverse('home'))
                else:
                    login_form.errors['user'] = 'User not found'
                    return render(request, "user/signup_login.html", {"login_form": login_form})
            else:
                return render(request, "user/signup_login.html", {"login_form": login_form})

        elif status == 'signup':
            register_form = EmailSignUpForm(request.POST)
            if register_form.is_valid():
                user = register_form.save(commit=False)
                user.is_active = False
                user.save()
                to_email = register_form.cleaned_data.get('email', "")
                mail_subject = 'Activate your blog account.'
                message = email_message_generator(request, user, "user/acc_active_email.html")
                email_sender.delay(message, to_email, mail_subject)
                return redirect('user:verify')
            else:
                return render(request, "user/signup_login.html", {"register_form": register_form})


def logout(request):
    _logout(request)
    return redirect('home')


def activate(request, uidb64, token):
    user = token_validator(uidb64, token)
    if user:
        user.is_active = True
        user.save()
        return redirect('user:login_register')
    else:
        return redirect("user:signup")


class ForgetPassword(View):

    def get(self, request):
        form = RestPasswordForm()
        return render(request, "user/forget_password.html", {"form": form})

    def post(self, request):
        form = RestPasswordForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get("user")
            mail_subject = 'reset your password'
            to_email = form.cleaned_data.get("email")
            message = email_message_generator(request, user, "user/reset_password_email.html",)
            email_sender.delay(message, to_email, mail_subject)
            return redirect("user:verify")
        else:
            render(request, "user/forget_password.html", {"form": form})


class PasswordReset(View):

    def get(self, request):
        uidb64 = request.GET.get("uidb64", "")
        token = request.GET.get("token", "")
        user = token_validator(uidb64, token)
        if user:
            form = SetPasswordForm(user)
            return render(request, "user/reset_password.html", {"form": form, "user": user})

    def post(self, request):
        email = request.POST.get("user")
        user = User.objects.get(email=email)
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
        else:
            render(request, "user/reset_password.html", {"form": form})


class WaitingForVerify(View):

    def get(self, request):
        return render(request, "user/verify.html", {})


@method_decorator(login_required, name="dispatch")
class UserProfileView(View):
    login_url = reverse_lazy("user:login_register")

    def get(self, request):
        factors = History.objects.filter(customer_id=request.user.id)
        wallet = Wallet.objects.get(user_id=request.user.id)
        form = UserUpdateForm(instance=request.user)
        ctx = {"factors": factors}
        ctx["form"] = form
        ctx["wallet"] = wallet
        ctx["devices"] = UserDevice.objects.filter(user_id=request.user.id)
        return render(request, "user/profile.html", context=ctx)

    def post(self, request):
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("user:profile")
        else:
            return redirect("user:profile", kwargs={"form": form})


class Factor(View):

    def get(request, id):
        factor = History.objects.get(id=id).values_list()
        return JsonResponse({"data": factor})

User/templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.email }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

User/templates/user/completeprofile.html
{% extends 'base.html' %}

{% block title %}Profile Page{% endblock title %}

{% block content %} 
    <h2>Profile Page</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
        <br><br>
        <a href="{% url 'home' %}">Back</a>
    </form>
{% endblock content %}

User/templates/user/erorr_404.html
{% extends "base.html" %}

{% block content %}

        <!-- Start of Main -->
        <main class="main">
            <!-- Start of Breadcrumb -->
            <nav class="breadcrumb-nav">
                <div class="container">
                    <ul class="breadcrumb bb-no">
                        <li><a href="demo1.html">صفحه اصلی </a></li>
                        <li>ارور 404</li>
                    </ul>
                </div>
            </nav>
            <!-- End of Breadcrumb -->

            <!-- Start of Page Content -->
            <div class="page-content error-404">
                <div class="container">
                    <div class="banner">
                        <figure>
                            <img src="{% static 'assets/images/pages/404.png' %}" alt="ارور 404"  
                                width="820" height="460" />
                        </figure>
                        <div class="banner-content text-center">
                            <h2 class="banner-title">
                                <span class="text-secondary">اوپس!!!</span> خطایی در سایت رخ داد!
                            </h2>
                            <p class="text-light">ممکن است در نشانی اینترنتی وارد شده غلط املایی وجود داشته باشد یا صفحه مورد نظر شما دیگر وجود نداشته باشد</p>
                            <a href="#" class="btn btn-dark btn-rounded btn-icon-right">برگشت به صفحه اصلی<i class="w-icon-long-arrow-left"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Page Content -->
        </main>
        <!-- End of Main -->
{% endblock content %}

User/templates/user/forget_password.html
{% extends "base.html" %}

{% block content %}
<h2>enter ur email</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {{form.errors}}
  <button type="submit">send</button>
</form>

{% endblock content %}

User/templates/user/reset_password.html
{% extends "base.html" %}

{% block content %}
<h2>enter ur password</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {{form.errors}}
  <input type="hidden" name="user" value="{{user}}">
  <button type="submit">reset password</button>
</form>

{% endblock content %}

User/templates/user/reset_password_email.html
{% load query_transform %}
{% autoescape off %}
Hi {{ user.email }},
Please click on the link to reset your password,http://{{ domain }}{% url 'user:passwordresest'%}?uidb64={{uid}}&token={{token}}
{% endautoescape %}

User/templates/user/signup_login.html
{% extends "base.html" %}

{% block content %}
<div class="login-popup" style="width: 50%; margin: 0 auto;">
    <div class="tab tab-nav-boxed tab-nav-center tab-nav-underline">
        <ul class="nav nav-tabs text-uppercase" role="tablist">
            <li class="nav-item">
                <a href="#sign-in" class="nav-link active">ورود</a>
            </li>
            <li class="nav-item">
                <a href="#sign-up" class="nav-link">ثبت نام</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="sign-in">
                <form method="post" action="{% url 'user:login_register' %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="login">
                    <input type="hidden" name="next_url" value="{{request.GET.next}}">
                    {{login_form.errors.user}}
                    <div class="form-group">
                        {{login_form.email.errors}}
                        <label>ایمیل : *</label>
                        {{login_form.email}}
                    </div>
                    <div class="form-group mb-0">
                        {{login_form.password.errors}}
                        <label>رمز عبور : *</label>
                        {{login_form.password}}
                    </div>
                    <div class="form-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-checkbox" id="remember" name="remember">
                        <label for="remember">مرا به خاطر بسپار</label>
                        <a href="{% url 'user:forget_password' %}">فراموشی رمز عبور</a>
                    </div>
                    <button type="submit" class="btn btn-primary">ورود</button>
                </form>
            </div>
            <div class="tab-pane" id="sign-up">
                <form method="post" action="{% url 'user:login_register' %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="signup">
                    <div class="form-group">
                        {{register_form.email.errors}}
                        <label>ایمیل : *</label>
                        {{register_form.email}}
                    </div>
                    <div class="form-group mb-5">
                        {{register_form.password1.errors}}
                        <label>رمز عبور *</label>
                        {{register_form.password1}}
                    </div>
                    <div class="form-group mb-5">
                        {{register_form.password2.errors}}
                        <label>تکرار رمز عبور *</label>
                        {{register_form.password2}}
                    </div>
                    <p>اطلاعات شخصی شما برای پشتیبانی از تجربه شما در سراسر این وب سایت، برای مدیریت دسترسی به حساب شما
                        و سایر اهدافی که در ما توضیح داده شده است، استفاده خواهد شد. <a href="#" class="text-primary">سیاست حفظ حریم خصوصی</a>.</p>
                    <a href="{% url 'salesman:signup' %}" class="d-block mb-5 text-primary">ثبت نام به عنوان فروشنده</a>
                    <div class="form-checkbox d-flex align-items-center justify-content-between mb-5">
                        <input type="checkbox" class="custom-checkbox" id="agree" name="agree" required="">
                        <label for="agree" class="font-size-md">با <a href="#"
                                                                                  class="text-primary font-size-md">سیاست حفظ حریم خصوصی</a> موافقم </label>
                    </div>
                    <button type="submit" class="btn btn-primary">ثبت نام</button>
                </form>
            </div>
        </div>
        <p class="text-center">ثبت نام با حساب های اجتماعی</p>
        <div class="social-icons social-icon-border-color d-flex justify-content-center">
            <a href="#" class="social-icon social-facebook w-icon-facebook"></a>
            <a href="#" class="social-icon social-twitter w-icon-twitter"></a>
            <a href="#" class="social-icon social-google fab fa-google"></a>
        </div>
    </div>
</div>
{% endblock content %}

User/templates/user/verify.html
{% extends 'base.html' %}  
  
{% block content %}  

<h1>please verify ur account in ur email</h1>

{% endblock content %}  

User/templates/user/wish_list.html
{% extends "base.html" %}

{% block content %}
        <!-- Start of Main -->
        <main class="main wishlist-page">
            <!-- Start of Page Header -->
            <div class="page-header">
                <div class="container">
                    <h1 class="page-title mb-0">علاقه مندیها</h1>
                </div>
            </div>
            <!-- End of Page Header -->

            <!-- Start of Breadcrumb -->
            <nav class="breadcrumb-nav mb-10">
                <div class="container">
                    <ul class="breadcrumb">
                        <li><a href="demo1.html">صفحه اصلی </a></li>
                        <li>علاقه مندیها</li>
                    </ul>
                </div>
            </nav>
            <!-- End of Breadcrumb -->

            <!-- Start of PageContent -->
            <div class="page-content">
                <div class="container">
                    <h3 class="wishlist-title">علاقه مندیهای من</h3>
                    <table class="shop-table wishlist-table">
                        <thead>
                            <tr>
                                <th class="product-name"><span>محصول</span></th>
                                <th></th>
                                <th class="product-price"><span>قیمت</span></th>
                                <th class="product-stock-status"><span>وضعیت انبار</span></th>
                                <th class="wishlist-action">اقدامات </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="product-thumbnail">
                                    <div class="p-relative">
                                        <a href="product-default.html">
                                            <figure>
                                                <img src="{% static 'assets/images/shop/7-1.jpg' %}" alt="product" width="300"
                                                    height="338">
                                            </figure>
                                        </a>
                                        <button type="submit" class="btn btn-close"><i
                                                class="fas fa-times"></i></button>
                                    </div>
                                </td>
                                <td class="product-name">
                                    <a href="product-default.html">
                                        تنه آسمان آبی
                                    </a>
                                </td>
                                <td class="product-price">
                                    <ins class="new-price">85000 تومان</ins>
                                </td>
                                <td class="product-stock-status">
                                    <span class="wishlist-in-stock">در انبار است </span>
                                </td>
                                <td class="wishlist-action">
                                    <div class="d-lg-flex">
                                        <a href="#"
                                            class="btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0">نمایش سریع </a>
                                        <a href="#" class="btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart">افزودن به سبد</a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="product-thumbnail">
                                    <div class="p-relative">
                                        <a href="product-default.html">
                                            <figure>
                                                <img src="{% static 'assets/images/shop/19-1.jpg' %}" alt="product" width="300" height="338">
                                            </figure>
                                        </a>
                                        <button type="submit" class="btn btn-close"><i
                                                class="fas fa-times"></i></button>
                                    </div>
                                </td>
                                <td class="product-name">
                                    <a href="product-default.html">
                                        انگشتر دست ساز
                                    </a>
                                </td>
                                <td class="product-price"><ins class="new-price">78000 تومان</ins></td>
                                <td class="product-stock-status">
                                    <span class="wishlist-in-stock">در انبار است </span>
                                </td>
                                <td class="wishlist-action">
                                    <div class="d-lg-flex">
                                        <a href="#"
                                            class="btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0">نمایش سریع </a>
                                        <a href="#" class="btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart">افزودن به سبد</a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="product-thumbnail">
                                    <div class="p-relative">
                                        <a href="product-default.html">
                                            <figure>
                                                <img src="{% static 'assets/images/shop/20.jpg' %}" alt="product" width="300"
                                                    height="338">
                                            </figure>
                                        </a>
                                        <button type="submit" class="btn btn-close"><i
                                                class="fas fa-times"></i></button>
                                    </div>
                                </td>
                                <td class="product-name">
                                    <a href="product-default.html">
                                        جا مدادی
                                    </a>
                                </td>
                                <td class="product-price"><ins class="new-price">54000 تومان</ins></td>
                                <td class="product-stock-status">
                                    <span class="wishlist-in-stock">در انبار است </span>
                                </td>
                                <td class="wishlist-action">
                                    <div class="d-lg-flex">
                                        <a href="#"
                                            class="btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0">نمایش سریع </a>
                                        <a href="#" class="btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart">افزودن به سبد</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="social-links">
                        <label>اشتراک در: </label>
                        <div class="social-icons social-no-color border-thin">
                            <a href="#" class="social-icon social-facebook w-icon-facebook"></a>
                            <a href="#" class="social-icon social-twitter w-icon-twitter"></a>
                            <a href="#" class="social-icon social-pinterest w-icon-pinterest"></a>
                            <a href="#" class="social-icon social-email far fa-envelope"></a>
                            <a href="#" class="social-icon social-whatsapp fab fa-whatsapp"></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of PageContent -->
        </main>
        <!-- End of Main -->

{% endblock content %}

       