API/urls.py
from django.urls import path, include

app_name = "api"

urlpatterns = [
    path('payment/', include("API.payment.urls", namespace="payment_api")),
    path('', include("API.product.urls", namespace="api_product")),
    path('user/',include("API.user.urls",namespace="user_api"))
]

Online_Store_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#outh
# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView


from .views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name="home"),
    path('product/', include('Product.urls', namespace='product')),
    path('news/', include('News.urls', namespace="news")),
    path('salesman/', include('Salesman.urls', namespace="salesman")),
    path('user/', include('User.urls', namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('Payment.urls', namespace="Payment")),
    #ouath :
    # path('o', TemplateView.as_view(template_name="outh.html")),
    # path('o/accounts/', include('allauth.urls')),
    # path('o/logout', LogoutView.as_view()),
    path('api/', include('API.urls',namespace="api"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Payment/urls.py
from django.urls import path
from .views import show_cart, checkout, payment_start, payment_return, payment_check, wallet_activation

app_name = 'Payment'

urlpatterns = [

    path('cart/', show_cart, name="show_cart"),
    path('checkout/', checkout, name="checkout"),
    path("wallet_activation/", wallet_activation, name="wallet_activation"),
    path('payment_start/', payment_start, name='payment_start'),
    path('return/', payment_return, name='payment_return'),
    path('check/<pk>', payment_check, name='payment_check'),
]

Product/urls.py
from django.urls import path

from .views import ProductDetail, ProductList, Search, add_comment, add_cart, delete_cart_item,WishListView

app_name = 'product'

urlpatterns = [
    path('product_detail/<str:slug>', ProductDetail.as_view(), name="product_detail"),
    path('product_list/<str:category>/', ProductList.as_view(), name="product_list"),
    path('', Search.as_view(), name="search"),
    path('add_comment/<str:product_slug>', add_comment, name="add_comment"),
    path('add_to_cart/<str:product_slug>', add_cart, name="add_to_cart"),
    path('delete_cart_item/<str:product_name>',delete_cart_item, name="delete_cart_item"),
    path('wishlist',WishListView.as_view(),name="wish_list")
]

User/urls.py
from unicodedata import name
from django.urls import path

from .views import (LoginRegisterView, WaitingForVerify, activate,
                    ForgetPassword, PasswordReset, logout, UserProfileView ,Factor)

app_name = "user"

urlpatterns = [
    path('verify/', WaitingForVerify.as_view(), name='verify'),
    path('login_register/', LoginRegisterView.as_view(), name='login_register'),
    path('logout/', logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),
    path('forget_password/', ForgetPassword.as_view(), name="forget_password"),
    path('passwordreset/', PasswordReset.as_view(), name='passwordresest'),
    path('profile/',UserProfileView.as_view(),name="profile"),
    path('factor/<int:id>/',Factor.as_view(),name="factor")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="وولـمارت - قالب چند منظوره و مارکت پلیس html">
    <meta name="author" content="JafarAbbasi">

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'assets/images/icons/favicon.png' %}">

    <!-- WebFont.js -->
    <script>
        WebFontConfig = {
            google: { families: ['Poppins:400,500,600,700'] }
        };
        (function (d) {
            var wf = d.createElement('script'), s = d.scripts[0];
            wf.src = 'assets/js/webfont.js';
            wf.async = true;
            s.parentNode.insertBefore(wf, s);
        })(document);
    </script>

    <link rel="preload" href="{% static 'assets/vendor/fontawesome-free/webfonts/fa-regular-400.woff2' %}" as="font" type="font/woff2"
        crossorigin="anonymous">
    <link rel="preload" href="{% static 'assets/vendor/fontawesome-free/webfonts/fa-solid-900.woff2' %}" as="font" type="font/woff2"
        crossorigin="anonymous">
    <link rel="preload" href="{% static 'assets/vendor/fontawesome-free/webfonts/fa-brands-400.woff2' %}" as="font" type="font/woff2"
            crossorigin="anonymous">
    <link rel="preload" href="{% static 'assets/fonts/wolmart87d5.ttf?png09e' %}" as="font" type="font/ttf" crossorigin="anonymous">

    <!-- Vendor CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}">

    <!-- Plugins CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/magnific-popup/magnific-popup.min.css' %}">

    <!-- Default CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/demo2.min.css' %}">
    {% block head %}
    {% endblock head %}
    <title>{% block title %}
    {% endblock title %}</title>
</head>
<body>
    {% block header %}{% include "header.html" %}{% endblock header %}
    {% block sidebar %} {% include "side.html" %}{% endblock sidebar %}
    {% block content %}{% endblock content %}
    {% block footer %}{% include "footer.html" %}{% endblock footer %}

    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.plugin/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.countdown/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'assets/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/floating-parallax/parallax.min.js' %}"></script>

    <!-- Main Js -->
    <script src="{% static 'assets/js/main.min.js' %}"></script>
</body>
</html>

templates/header.html
{%load static%}
{% load main_page_templates_tags %}
{% load price_of_cart %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="page-wrapper">
        <!-- Start of Header -->
        <header class="header">
            <div class="header-top">
                <div class="container">
                    <div class="header-right pr-0">
                        <div class="dropdown">
                            <a href="#currency">تومان </a>
                            <div class="dropdown-box">
                                <a href="#USD">تومان </a>
                                <a href="#EUR">دلار </a>
                            </div>
                        </div>
                        <!-- End of DropDown Menu -->

                        <div class="dropdown">
                            <a href="#language"><img src="{%static 'assets/images/flags/eng.png'%}" alt="ENG Flag" width="14"
                                    height="8" class="dropdown-image" /> تومان </a>
                            <div class="dropdown-box">
                                <a href="#ENG">
                                    <img src="{%static 'assets/images/flags/eng.png'%}" alt="ENG Flag" width="14" height="8"
                                        class="dropdown-image" />
                                    فارسی    </a>
                                <a href="#FRA">
                                    <img src="{%static 'assets/images/flags/fra.png'%}" alt="FRA Flag" width="14" height="8"
                                        class="dropdown-image" />
                                   انگلیسی </a>
                            </div>
                        </div>
                        <!-- End of Dropdown Menu -->
                        <span class="divider d-lg-show"></span>
                        <a href="blog.html" class="d-lg-show">وبلاگ </a>
                        <a href="contact-us.html" class="d-lg-show">تماس با ما </a>
                        <a href="{% url 'user:profile' %}" class="d-lg-show">حساب کاربری من </a>
                        {% if request.user.email %}
                        <a href="{% url 'user:logout' %}" class="d-lg-show"><i
                                class="w-icon-account"></i>خروج  </a>
                        {% else %}
                        <a href="{% url 'user:login_register' %}" class="d-lg-show"><i
                                class="w-icon-account"></i>ورود  </a>
                        <span class="delimiter d-lg-show">/</span>
                        <a href="{% url 'user:login_register' %}" class="ml-0 d-lg-show">ثبت نام </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- End of Header Top -->

            <div class="header-middle">
                <div class="container">
                    <div class="header-left mr-md-4">
                        <a href="{%url 'home'%}" class="mobile-menu-toggle  w-icon-hamburger">
                        </a>
                        <a href="{%url 'home'%}" class="logo ml-lg-0">
                            <img src="{%static 'assets/images/demos/demo2/hlogo.png'%}" alt="logo" width="144" height="45" />
                        </a>
                        <nav class="main-nav">
                            <ul class="menu">
                                <li class="active">
                                    <a href="{%url 'home'%}">صفحه اصلی </a>
                                </li>
                                <li>
                                    <a href="shop-banner-sidebar.html">کلاب فروشندگان </a>
                                </li>
                                <li>
                                    <a href="vendor-dokan-store.html">کلاب مشتریان </a>
                                </li>
                                <li>
                                    <a href="blog.html">وبلاگ </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="header-right ml-4">
                        <div class="header-call d-xs-show d-lg-flex align-items-center">
                            <a href="tel:#" class="w-icon-call"></a>
                            <div class="call-info d-xl-show">
                                <h4 class="chat font-weight-normal font-size-md text-normal ls-normal text-light mb-0">
                                    <a href="mailto:#" class="text-capitalize">چت زنده </a> یا :</h4>
                                <a href="tel:#" class="phone-number font-weight-bolder ls-50">0(800)123-456</a>
                            </div>
                        </div>
                        <a class="wishlist label-down link d-xs-show" href="wishlist.html">
                            <i class="w-icon-heart"></i>
                            <span class="wishlist-label d-lg-show">لیست علاقه مندیها </span>
                        </a>
                        <a class="compare label-down link d-xs-show" href="compare.html">
                            <i class="w-icon-compare"></i>
                            <span class="compare-label d-lg-show">مقایسه کردن </span>
                        </a>
                        <div class="dropdown cart-dropdown mr-0 mr-lg-2">
                            <div class="cart-overlay"></div>
                            <a href="{% url 'Payment:show_cart' %}" class="cart-toggle label-down link">
                                <i class="w-icon-cart">
                                    <span class="cart-count">{{cart|length}}</span>
                                </i>
                                <span class="cart-label">سبد خرید </span>
                            </a>
                            <div class="dropdown-box">
                                <div class="products">
                                    {% for product, detail in cart.items %}
                                    <div class="product product-cart">
                                        <div class="product-detail">
                                            <a href="{% url 'product:product_detail' detail.3 %}" class="product-name">{{product}}</a>
                                            <div class="price-box">
                                                <span class="product-quantity">{{detail.0}}</span>
                                                <span class="product-price">{{detail.2}}</span>
                                            </div>
                                        </div>
                                        <figure class="product-media">
                                            <a href="{% url 'product:product_detail' detail.3 %}">
                                                <img src="{{detail.1}}" alt="product" height="84"
                                                    width="94" />
                                            </a>
                                        </figure>
                                        <button class="btn btn-link btn-close">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </div>
                                    {% endfor %}
                                </div>
                                {% sum_of_cart cart as cart_price %}
                                <div class="cart-total">
                                    <label>مجموع کل: </label>
                                    <span class="price">{{cart_price}} تومان</span>
                                </div>

                                <div class="cart-action">
                                    <a href="{% url 'Payment:show_cart' %}" class="btn btn-dark btn-outline btn-rounded">نمایش سبد </a>
                                    <a href="{% url 'Payment:checkout' %}" class="btn btn-primary  btn-rounded">پرداخت </a>
                                </div>
                            </div>
                            <!-- End of Dropdown Box -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Header Middle -->

            <div class="header-bottom sticky-content fix-top sticky-header">
                <div class="container">
                    <div class="inner-wrap">
                        <div class="header-left flex-1">
                            <div class="dropdown category-dropdown has-border" data-visible="true">
                                <a href="#" class="category-toggle" role="button" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="true" data-display="static"
                                    title="جستجوی دسته بندیها">
                                    <i class="w-icon-category"></i>
                                    <span>کاووش دسته بندیها </span>
                                </a>

                                <div class="dropdown-box">
                                    <ul class="menu vertical-menu category-menu">
                                    {% for category in p_category %}
                                        <li>
                                            <a href="#">
                                                <i class="w-icon-home"></i>{{category.name}}
                                            </a>
                                            <ul class="megamenu">
                                                {% get_sub_cat category as sub_categorys%}
                                                {% for sub_category in sub_categorys %}
                                                <li>
                                                    <h4 class="menu-title">{{sub_category.name}}</h4>
                                                    <hr class="divider">
                                                    {% get_sub_cat sub_category as sub_sub_categorys%}
                                                    <ul>
                                                        {% for sub_sub_category in sub_sub_categorys %}
                                                            <li><a href="{% url 'product:product_list' sub_sub_category.name %}">{{sub_sub_category.name}}</a></li>
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    {%endfor%}                                        
                                    </ul>
                                        
                                </div>
                            </div>
                            <form method="get" action="{% url 'product:search' %}" class="header-search hs-expanded hs-round d-none d-md-flex input-wrapper mr-4 ml-4">
                                <div class="select-box">
                                    <select id="category" name="category">
                                        <option value="">تمام دسته بندی ها</option>
                                        {% for category in p_category %}
                                        <option value="{{category.name}}">{{category.name}} </option>
                                        {%endfor%}
                                    </select>
                                </div>
                                <input type="text" class="form-control" name="search" id="search"
                                    placeholder="جستجو ..." required />
                                <button class="btn btn-search" type="submit"><i class="w-icon-search"></i>
                                </button>
                            </form>
                        </div>
                        <div class="header-right pr-0 ml-4">
                            <a href="#" class="d-xl-show mr-6"><i class="w-icon-map-marker mr-1"></i>پیگیری سفارش</a>
                            <a href="#"><i class="w-icon-sale"></i>فروش ویژه </a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- End of Header -->
</body>
</html>

templates/outh.html
{% load socialaccount %}
<html>
<body>
<h1>My Google OAuth Project </h1>
{% if user.is_authenticated %}
  <p>Welcome, You are logged in as {{ user.username }}</p>
{% else %}
  <a href="{% provider_login_url 'google' %}">Login With Google</a>
{% endif %}
</body>
</html>

templates/side.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>