API/payment/urls.py
from django.urls import path

from .payment_api_view import CartApiView

app_name = "payment_api"


urlpatterns = [
    path('cart/',CartApiView.as_view(),name="cart_api"),
]

API/urls.py
from django.urls import path, include

app_name = "api"

urlpatterns = [
    path('payment/', include("API.payment.urls", namespace="payment_api")),
    path('', include("API.product.urls", namespace="api_product")),
    path('user/',include("API.user.urls",namespace="user_api"))
]

Online_Store_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#outh
# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView


from .views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name="home"),
    path('product/', include('Product.urls', namespace='product')),
    path('news/', include('News.urls', namespace="news")),
    path('salesman/', include('Salesman.urls', namespace="salesman")),
    path('user/', include('User.urls', namespace="user")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('Payment.urls', namespace="Payment")),
    #ouath :
    # path('o', TemplateView.as_view(template_name="outh.html")),
    # path('o/accounts/', include('allauth.urls')),
    # path('o/logout', LogoutView.as_view()),
    path('api/', include('API.urls',namespace="api"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Payment/urls.py
from django.urls import path
from .views import show_cart, checkout, payment_start, payment_return, payment_check, wallet_activation

app_name = 'Payment'

urlpatterns = [

    path('cart/', show_cart, name="show_cart"),
    path('checkout/', checkout, name="checkout"),
    path("wallet_activation/", wallet_activation, name="wallet_activation"),
    path('payment_start/', payment_start, name='payment_start'),
    path('return/', payment_return, name='payment_return'),
    path('check/<pk>', payment_check, name='payment_check'),
]

Product/urls.py
from django.urls import path

from .views import ProductDetail, ProductList, Search, add_comment, add_cart, delete_cart_item,WishListView

app_name = 'product'

urlpatterns = [
    path('product_detail/<str:slug>', ProductDetail.as_view(), name="product_detail"),
    path('product_list/<str:category>/', ProductList.as_view(), name="product_list"),
    path('', Search.as_view(), name="search"),
    path('add_comment/<str:product_slug>', add_comment, name="add_comment"),
    path('add_to_cart/<str:product_slug>', add_cart, name="add_to_cart"),
    path('delete_cart_item/<str:product_name>',delete_cart_item, name="delete_cart_item"),
    path('wishlist',WishListView.as_view(),name="wish_list")
]

Payment/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class History(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)
    cart = models.JSONField(default=dict)
    price = models.CharField(max_length=30)
    payment_method = models.CharField(max_length=30)
    tracking_code = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f"{self.customer.email} --- {self.tracking_code}"


class Wallet(models.Model):
    cash = models.BigIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="wallet",null=True)
    create_date = models.DateField(auto_now=True)
    is_active = models.BooleanField(default=False)


class GateWaysModel(models.Model):
    
    order_id = models.TextField()
    payment_id = models.TextField()
    amount = models.IntegerField()
    date = models.TextField(default='-')
    card_number = models.TextField(default="****")
    idpay_track_id = models.IntegerField(default=0000)
    bank_track_id = models.TextField(default=0000)
    status = models.IntegerField(default=0)
    email = models.EmailField(null=True)

    def __str__(self):
        return str(self.pk) + "  |  " + self.order_id + "  |  " + str(self.status)

Payment/forms.py
from django import forms

from Payment.models import Wallet


class WalletUpdateForm(forms.Form):
        
    amount = forms.IntegerField()

Payment/views.py
import uuid
import json

from django.contrib.auth import get_user_model, login
from django.shortcuts import render, redirect, get_object_or_404
from django.core.cache import caches
from django.urls import reverse_lazy
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect

from decouple import config
from idpay.api import IDPayAPI

from Product.utils import dict_decoder
from .models import GateWaysModel, History, Wallet
from .forms import WalletUpdateForm

User = get_user_model()


def payment_init():
    base_url = config('BASE_URL', default='http://localhost:8000', cast=str)
    api_key = config('IDPAY_API_KEY', default='1c86dfd5-bb82-4fde-b340-0b33af756e77', cast=str)
    sandbox = config('IDPAY_SANDBOX', default=True, cast=bool)

    return IDPayAPI(api_key, base_url, sandbox)


@login_required(login_url=reverse_lazy('user:login_register'))
def payment_start(request):
    if request.method == 'POST':

        order_id = uuid.uuid1()
        amount = request.POST.get('amount')

        payer = {
            'name': request.user.username,
            'phone': request.user.phone_number,
            'email': request.user.email,
            'desc': request.POST.get('desc', ""),
        }

        record = GateWaysModel(order_id=order_id, amount=int(amount), email=request.user.email)
        record.save()
        idpay_payment = payment_init()
        result = idpay_payment.payment(str(order_id), amount, "/payment/return/", payer)

        if 'id' in result:
            record.status = 1
            record.payment_id = result['id']
            record.save()

            return redirect(result['link'])

        else:
            txt = result['message']
    else:
        txt = "Bad Request"

    return render(request, 'error.html', {'txt': txt})


@csrf_exempt
def payment_return(request):
    if request.method == 'POST':

        pid = request.POST.get('id')
        status = request.POST.get('status')
        pidtrack = request.POST.get('track_id')
        order_id = request.POST.get('order_id')
        amount = request.POST.get('amount')
        card = request.POST.get('card_no')
        date = request.POST.get('date')

        # print(email)

        if GateWaysModel.objects.filter(order_id=order_id, payment_id=pid, amount=amount, status=1).count() == 1:

            idpay_payment = payment_init()

            payment = GateWaysModel.objects.get(payment_id=pid, amount=amount)
            payment.status = status
            payment.date = str(date)
            payment.card_number = card
            payment.idpay_track_id = pidtrack
            payment.save()

            if str(status) == '10':
                result = idpay_payment.verify(pid, payment.order_id)

                if 'status' in result:

                    payment.status = result['status']
                    payment.bank_track_id = result['payment']['track_id']
                    payment.save()

                    redis_cache = caches['default']
                    redis_client = redis_cache.client.get_client()
                    paid_cart = dict_decoder(redis_client.hgetall(payment.email))
                    keys = list(paid_cart.keys())
                    for key in keys:
                        redis_client.hdel(payment.email, key)
                    user = get_object_or_404(User, email=payment.email)
                    login(request, user)
                    history = History.objects.create(customer=user, cart=json.dumps(paid_cart), price=amount,
                                                     payment_method="درگاه بانکی",
                                                     tracking_code=result['payment']['track_id'])
                    ctx = {
                        'history': history,
                        "paid_cart": paid_cart
                    }
                    return render(request, "payment/order.html", context=ctx)

                else:
                    txt = result['message']

            else:
                txt = "Error Code : " + str(status) + "   |   " + "Description : " + idpay_payment.get_status(status)

        else:
            txt = "Order Not Found"

    else:
        txt = "Bad Request"

    return render(request, 'error.html', {'txt': txt})


def payment_check(request, pk):
    payment = GateWaysModel.objects.get(pk=pk)

    idpay_payment = payment_init()
    result = idpay_payment.inquiry(payment.payment_id, payment.order_id)

    if 'status' in result:
        payment.status = result['status']
        payment.idpay_track_id = result['track_id']
        payment.bank_track_id = result['payment']['track_id']
        payment.card_number = result['payment']['card_no']
        payment.date = str(result['date'])
        payment.save()

    return render(request, 'error.html', {'txt': result['message']})


def show_cart(request):
    return render(request, 'payment/cart.html')


def checkout(request):
    return render(request, 'payment/checkout.html')


def wallet_activation(request):
    if request.method == "GET":
        wallet = Wallet.objects.get(user_id=request.user.id)
        wallet.is_active = True
        wallet.save()
        return redirect("user:profile")


class IncreaseWalletCash(View):

    def get(self, request):
        pass

    def post(self, request):
        pass

Payment/templates/payment/cart.html
{% extends "base.html" %}
{% load static %}
{% load price_of_cart %}


{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.min.css' %}">
{% endblock head %}

{% block content %}
<main class="main cart">

    <nav class="breadcrumb-nav">
        <div class="container">
            <ul class="breadcrumb shop-breadcrumb bb-no">
                <li class="active"><a href="{% url 'Payment:show_cart' %}">سبد خرید فروشگاه </a></li>
                <li><a href="{% url 'Payment:checkout' %}">پرداخت </a></li>
                <li><a href="#">سفارش کامل شد</a></li>
            </ul>
        </div>
    </nav>

    <div class="page-content">
        <div class="container">
            <div class="row gutter-lg mb-10">
                <div class="col-lg-8 pr-lg-4 mb-6">
                    <table class="shop-table cart-table">
                        {% if cart %}
                        <thead>
                        <tr>
                            <th class="product-name"><span>محصول </span></th>
                            <th></th>
                            <th class="product-price"><span>قیمت</span></th>
                            <th class="product-quantity"><span>تعداد</span></th>
                            <th class="product-subtotal"><span>جمع کل</span></th>
                        </tr>
                        </thead>
                        {% endif %}
                        <tbody>
                        {% for product, detail in cart.items %}
                        <tr>
                            <td class="product-thumbnail">
                                <div class="p-relative">
                                    <a href="{%url 'product:product_detail' detail.3 %}">
                                        <figure>
                                            <img src="{{detail.1}}" alt="product"
                                                 width="300" height="338">
                                        </figure>
                                    </a>
                                    <button type="submit" class="btn btn-close"><a href="{% url 'product:delete_cart_item' product  %}"><i
                                            class="fas fa-times"></i></a></button>
                                </div>
                            </td>
                            <td class="product-name">
                                <a href="{%url 'product:product_detail' detail.3 %}">
                                    {{product}}
                                </a>
                            </td>
                            <td class="product-price"><span class="amount">{{detail.2}}</span></td>
                            <td class="product-quantity">
                                <div class="input-group">
                                    {{detail.0}}
                                </div>
                            </td>
                            <td class="product-subtotal">
                                <span class="amount">{% widthratio detail.0 1 detail.2 as p %}{{p}}</span>
                            </td>
                        </tr>
                        {%empty%}
                        <div>
                            <h3><strong>سبد خرید شما خالی است!</strong></h3>
                            <h4> می‌توانید برای مشاهده محصولات بیشتر به فروشگاه بروید. </h4> <a href="{% url 'home' %}"
                                                                                                class="btn btn-primary cart-btn-transform m-3"
                                                                                                data-abc="true">فروشگاه</a>
                        </div>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if cart %}
                    <div class="cart-action mb-6">
                        <button type="submit" class="btn btn-rounded btn-default btn-clear" name="clear_cart"
                                value="پاک کردن سبد">پاک کردن سبد
                        </button>
                        <button type="submit" class="btn btn-rounded btn-update disabled" name="update_cart"
                                value="بروزرسانی سبد">بروزرسانی سبد
                        </button>
                    </div>
                    <form class="coupon">
                        <h5 class="title coupon-title font-weight-bold text-uppercase">انواع کد تخفیف </h5>
                        <input type="text" class="form-control mb-4" placeholder="وارد کردن کد تخفیف..." required/>
                        <button class="btn btn-dark btn-outline btn-rounded">اعمال کد</button>
                    </form>
                </div>
                <div class="col-lg-4 sticky-sidebar-wrapper">
                    <div class="sticky-sidebar">
                        <div class="cart-summary mb-4">
                            <h3 class="cart-title text-uppercase">مجموع سبد خرید</h3>
                            <div class="cart-subtotal d-flex align-items-center justify-content-between">
                                <label class="ls-25">جمع کل</label>
                                <span></span>
                            </div>
                            <hr class="divider">

                            <ul class="shipping-methods mb-2">
                                <li>
                                    <label class="shipping-title text-dark font-weight-bold">حمل و نقل</label>
                                </li>
                                <li>
                                    <div class="custom-radio">
                                        <input type="radio" id="free-shipping" class="custom-control-input"
                                               name="shipping">
                                        <label for="free-shipping"
                                               class="custom-control-label color-dark">ارسال رایگان</label>
                                    </div>
                                </li>
                                <li>
                                    <div class="custom-radio">
                                        <input type="radio" id="local-pickup" class="custom-control-input"
                                               name="shipping">
                                        <label for="local-pickup"
                                               class="custom-control-label color-dark">وانت محلی</label>
                                    </div>
                                </li>
                                <li>
                                    <div class="custom-radio">
                                        <input type="radio" id="flat-rate" class="custom-control-input"
                                               name="shipping">
                                        <label for="flat-rate" class="custom-control-label color-dark">نرخ ثابت:
                                            78000 تومان</label>
                                    </div>
                                </li>
                            </ul>

                            <div class="shipping-calculator">
                                <p class="shipping-destination lh-1">حمل و نقل به <strong>کدام کشور؟</strong>.</p>

                                <form class="shipping-calculator-form">
                                    <div class="form-group">
                                        <div class="select-box">
                                            <select name="country" class="form-control form-control-md">
                                                <option value="default" selected="selected">ترکیه

                                                </option>
                                                <option value="us">ترکیه</option>
                                                <option value="uk">آمریکا</option>
                                                <option value="fr">فرانسه</option>
                                                <option value="aus">هلند</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="select-box">
                                            <select name="state" class="form-control form-control-md">
                                                <option value="default" selected="selected">کالیفرنیا
                                                </option>
                                                <option value="ohaio">اویاهو</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control form-control-md" type="text"
                                               name="town-city" placeholder="شهر / بخش">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control form-control-md" type="text"
                                               name="zipcode" placeholder="کد پستی">
                                    </div>
                                    <button type="submit" class="btn btn-dark btn-outline btn-rounded">بروز کردن سبد
                                    </button>
                                </form>
                            </div>
                            {%sum_of_cart cart as cart_price%}

                            <hr class="divider mb-6">
                            <div class="order-total d-flex justify-content-between align-items-center">
                                <label>مجموع خرید</label>
                                <span class="ls-50">{{cart_price}}</span>
                            </div>
                            <a href="{%url 'Payment:checkout' %}"
                               class="btn btn-block btn-dark btn-icon-right btn-rounded  btn-checkout">
                                برای تسویه حساب ادامه دهید<i class="w-icon-long-arrow-left"></i></a>
                        </div>
                        {% else %}
                        <div class="container-fluid mt-100">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Cart</h5>
                                        </div>
                                        <div class="card-body cart">
                                            <div class="col-sm-12 empty-cart-cls text-center"><img
                                                    src="https://i.imgur.com/dCdflKN.png" width="130" height="130"
                                                    class="img-fluid mb-4 mr-3">
                                                <h3><strong>Your Cart is Empty</strong></h3>
                                                <h4>Add something to make me happy :)</h4> <a href="#"
                                                                                              class="btn btn-primary cart-btn-transform m-3"
                                                                                              data-abc="true">continue
                                                    shopping</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

Payment/templates/payment/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="IDPay">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title> IDPay </title>
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="https://idpay.ir">IDPay</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/requirement">Requirements</a>
            <a class="nav-item nav-link" href="/about-me">About</a>

          </div>
        </div>
      </nav>

      <br/> <br/> <br/> <br/>

    <div class="container">
        <div class="row">
          <div class="col-12">


            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Order ID</th>
                    <th scope="col">Payment ID</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Card Number</th>
                    <th scope="col">IDPay Track ID</th>
                    <th scope="col">Bank Track ID</th>
                    <th scope="col">Status</th>
                    <th scope="col">Check</th>
                  </tr>
                </thead>
                <tbody>

                    {% for payment in payments %}

                  <tr>
                    <th scope="row">{{payment.pk}}</th>
                    <td>{{payment.order_id}}</td>
                    <td>{{payment.payment_id}}</td>
                    <td>{{payment.amount}}</td>
                    <td>{{payment.card_number }}</td>
                    <td>{{payment.idpay_track_id}}</td>
                    <td>{{payment.bank_track_id}}</td>
                    <td>{{payment.status}}</td>
                    <td><a href="{%url 'payment_check' pk=payment.pk %}">Check</a></td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>


          </div>
        </div>
      </div>

      <br/> <br/>

      <div class="container">
            <div class="row">
            <div class="col-3"></div>
              <div class="col-6">

                <form action="{%url 'Payment:payment_start' %}" method="POST">
                    {% csrf_token %}

                    <input style="width: 100%;" type="number" name="amount" placeholder="Amount" required>
                    <br/> <br/>

                    <input style="width: 100%;" type="text" name="name" placeholder="Name" required>
                    <br/> <br/>

                    <input style="width: 100%;" type="text" name="phone" placeholder="Phone">
                    <br/> <br/>

                    <input style="width: 100%;" type="mail" name="mail" placeholder="MAil">
                    <br/> <br/>

                    <input style="width: 100%;" type="text" name="desc" placeholder="Description">
                    <br/> <br/>

                    <button style="width: 100%;"  type="submit" class="btn btn-primary">Start Payment</button>

                </form>

              </div>
              <div class="col-3"></div>
            </div>
          </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

Payment/templates/payment/wallet.html
{% extends "base.html" %}

{% block content %}
<h2>موجودی{{holding}}ریال</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {{form.errors}}
  <button type="submit">send</button>
</form>

{% endblock content %}

Payment/templates/payment/walletcreation.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {{form.errors}}
  <button type="submit">ساخت کیف پول</button>
</form>

{% endblock content %}